 File to develop functions and text

```{r ll}
sto::ll("dplyr sto stringr")
options(browser = "firefox")
```
```{r text}
library(sotu)
# the metadata, to see which discourse we want.
# sotu_meta
text <- sotu_text[240]
```
```{r available}
available::available("codifyR") # TRUE
```
```{r build_readme/  vignette}
usethis::use_readme_rmd()
devtools::build_vignettes("vignettes")
devtools::build_vignettes("vignettes/codifing.Rmd")
These files can be checked into version control, so they can be viewed with browseVignettes() and vignette() if the package has been loaded with load_all()
browseVignettes() # mostra todos vignetes de todos pacotes
vignette()
# usethis::use_readme_rmd()
usethis::use_github()
usethis::use_github_links() #  If a package is already connected to a remote GitHub repository, usethis::use_github_links() can be called to just add the relevant links to DESCRIPTION.'use_github_links()'
# usethis::use_data_table() # creates all the boilerplate. https://usethis.r-lib.org/reference/use_data_table.html
devtools::build_readme() # locates your README.Rmd and builds it into a README.md
devtools::build_manual() # Create package pdf manual
# usethis::use_pkgdown() # is a function you run once and it does the initial, minimal setup necessary to start using pkgdown:
pkgdown::build_site_github_pages()
# pkgdown::build_site() # is a function you’ll call repeatedly, to re-render your site locally. In an extremely barebones package, https://r-pkgs.org/website.html
# devtools::build_site() # Execute pkgdown build_site in a package
# build_site() is a shortcut for pkgdown::build_site()
```
## country code
```{r countrycode select}
library(countrycode)

codelist_panel |>
  select(ar5) |>
  count(ar5)
codelist_panel |>
  select(unhcr.region) |>
  count(unhcr.region)
codelist_panel |>
  select(eurocontrol_pru) |>
  count(eurocontrol_pru)
continent_country <- codelist_panel |>
  select(continent, country.name.en) |>
  unique() |>
  arrange(continent)

continent_country <- codelist_panel |>
  select(eurocontrol_pru, country.name.en) |>
  unique() |>
  arrange(eurocontrol_pru) |>
  rename(continent = eurocontrol_pru, country = country.name.en)
```
col 1: categoria, 
col 2: termos ou padrão, 
col 3: cor
col 4: descrição que irá aparecer quando o mouse passar por cima da palavra. Se vazio, usa a coluna 1
```{r DF}
# lapply(color_text)
DF <- continent_country
DF |> filter()
```
```{r fun colorize}
colorize <- function(DF, colors = color_palette) {
  # todo checar n de colunas?
  colors <- colors[1:nrow(DF)]

  DF |> dplyr::mutate(color = colors)
  # colors
}

colorize(DF2) |> pull(color)
```
```{r DF2  }
cols <- colnames(DF)
DF2 <- DF |>
  group_by(continent) |>
  # group_by( !!{{cols[1]}} ) |>
  # group_by( !!cols[1] ) |>
  # with(cols[1], group_by() )  |>
  # summarise(items := !!{{paste(cols[2]}} , collapse = "|"))
  summarise(items = paste(eval(sym(cols[2])), collapse = "|")) |>
  # summarise(items = paste(country.name.en, collapse = "|"))
  colorize(color_palette3) |>
  # as.data.frame() |>
  nothing()
```
```{r color_text}
text |>
  color_text(
    pattern = DF2[1, 2],
    # color_txt = "yellow",
    color_txt = DF2[1, "color"],
    mouseover_txt = DF2[1, 1]
  ) |>
  color_text(
    pattern = DF2[2, 2],
    color_txt = DF2[2, "color"],
    mouseover_txt = DF2[2, 1]
  ) |>
  color_text(
    pattern = DF2[3, 2],
    color_txt = DF2[3, "color"],
    mouseover_txt = DF2[3, 1]
  ) |>
  color_text(
    pattern = DF2[4, 2],
    color_txt = DF2[4, "color"],
    mouseover_txt = DF2[4, 1]
  ) |>
  color_text(
    pattern = DF2[5, 2],
    color_txt = DF2[5, "color"],
    mouseover_txt = DF2[5, 1]
  ) |>
  color_text(
    pattern = DF2[6, 2],
    color_txt = DF2[6, "color"],
    mouseover_txt = DF2[6, 1]
  ) |>
  color_text(
    pattern = DF2[7, 2],
    color_txt = DF2[7, "color"],
    mouseover_txt = DF2[7, 1]
  ) |>
  color_text(
    pattern = DF2[8, 2],
    color_txt = "yellow",
    # color_txt = DF2[8, "color"],
    mouseover_txt = DF2[8, 1]
  ) |>
  # color_text(
  #    # pattern = DF2[8,2],
  #    pattern = "Antigua & Barbuda|Argentina|Bahamas|Barbados|Belize|Bolivia|Brazil|Chile|Colombia|Costa Rica|Cuba|Dominica|Dominican Republic|Ecuador|El Salvador|Grenada |Guatemala|Guyana|Haiti|Honduras|Jamaica|Mexico|Nicaragua|Panama|Paraguay|Peru|St. Kitts & Nevis|St. Lucia|St. Vincent & Grenadines|Suriname|Trinidad & Tobago|Uruguay|Venezuela",
  #    color_txt = DF2[8, "color"],
  #    # mouseover_txt = DF2[8,1]) |>
  #    mouseover_txt = "Sudamerica") |>
  # }) |> unlist()  |> paste(collapse = " ")  |>
  build_html(title_page = "SOTU - Trump", name = "./dev/sotu_.html")
```
```{r color_text debug}
text |>
  # color_text(
  #    pattern = DF2[2,2],
  #    color_txt = DF2[2, "color"],
  #    mouseover_txt = DF2[2,1]) |>
  # color_text(
  #    pattern = DF2[6,2],
  #    color_txt = DF2[6, "color"],
  #    mouseover_txt = DF2[6,1]) |>
  color_text(
    # pattern = DF2[8,2],
    pattern = "Antigua & Barbuda|Argentina|Bahamas|Barbados|Belize|Bolivia|Brazil|Chile|Colombia|Costa Rica|Cuba|Dominica|Dominican Republic|Ecuador|El Salvador|Grenada |Guatemala|Guyana|Haiti|Honduras|Jamaica|Mexico|Nicaragua|Panama|Paraguay|Peru|St. Kitts & Nevis|St. Lucia|St. Vincent & Grenadines|Suriname|Trinidad & Tobago|Uruguay|Venezuela",
    color_txt = DF2[8, "color"],
    # mouseover_txt = DF2[8,1]) |>
    mouseover_txt = "Sudamerica"
  ) |>
  # }) |> unlist()  |> paste(collapse = " ")  |>
  build_html(title_page = "SOTU - Trump", name = "./dev/sotu_.html")
```
```{r fun}
# x =1
text2 <- text
# text2 <-
lapply(1:nrow(DF2), \(x) {
  color_text(
    text = text2,
    pattern = DF2[x, 2],
    # color_txt = "yellow",
    color_txt = DF2[x, "color"],
    mouseover_txt = DF2[x, 1]
  )
}) |>
  unlist() |>
  paste(collapse = " ") |>
  build_html(title_page = "SOTU - Trump", name = "./dev/sotu_.html")
```
```{r fun codify_df}
codify <- function(text, categories) {
  # categories <-  DF2[1:8,]
  # categories <-  continent_country
  categories <- categories |> as.data.frame()
  c_names <- colnames(categories)

  if ("color" %in% c_names) {
    categories |> colorize()

  }

    for (i in 1:nrow(categories)) {
      # message(i, "|#|", DF2[i,2], "|#|", DF2[i,"color"], "|>|",  DF2[i,1])
      # message(" ")
      text <- text |>
        color_text(
          pattern = DF2[i, 2],
          color_txt = DF2[i, "color"],
          mouseover_txt = DF2[i, 1]
        )
    }
  }
  return(text)
}

codify(text, DF2[1:8, ]) |>
  build_html(title_page = "SOTU - Trump", name = "./dev/sotu_.html")
```
```{r append country continent}
unique(continent_country$continent)

DF_append <- tribble(
  ~continent, ~country,
  "Northern America", "U\\.S\\.(A\\.)?|United States (of America)?|North America",
  "Southern America", "South America",
  "Middle East", "Middle Eeast",
  "Eurocontrol", "Europ",
  "Africa", "Africa",
  "Asia", "Asia"
)

continent_country <- continent_country |> rbind(DF_append)
```
```{r fun combine/collapse categories}
#' given a dataframe with categories, it collapses the categories into one line in regex pattern
collapse_categories <- function(DF) {
  col_names <- colnames(DF)

  DF |>
    # group_by( continent ) |>
    group_by(category = eval(sym(col_names[1]))) |>
    summarise(items = paste(eval(sym(col_names[2])), collapse = "|"))
}
collapse_categories(continent_country)
```
```{r}
continent_country |>
  collapse_categories() |>
  colorize(color_palette) |>
  codify_df(text, df_categories = _) |>
  build_html(title_page = "SOTU - Trump", name = "./dev/sotu_.html")
```
```{r fun words categories}
collapse_words <- function(text) {
  sto::s2v(text) |> paste(collapse = "|")
}


conslusao <- s2v("(?i)Conclus[aã]o conclui-se por_conseguinte portanto") |> paste(collapse = "|")
```







L







codifyR can uses yaml format to store the categories 

```{yml}
category_name:
  keys: words sepated by space, and compounded words (like "New York") binded by underscore, like "New_York".
  color: lightgray
  description: A brief descritpion of what this category is
```




