#' count categories
#'
#' from an html file, count the categories generated and returns some basic 
#' statistics, like frequency of each category in text, as well as the frequency
#' of terms from each category.
#'
count_categories <- function(file) {
  # pagina <- "uber_base_completa.html" |> #file.exists()
  pagina <- file |> #file.exists()
    rvest::read_html(encoding="utf8")

  span_categories <- pagina |> rvest::html_elements('span[title]') |> rvest::html_attr("title")
# pagina |> rvest::html_elements('span[title="vinculo"]') |> rvest:: html_text()

  categories_count <- span_categories |> sto::count_vec() 

  names(categories_count) <- c("category", "freq")

  lista <- lapply(categories_count$x, \(x) {
    pagina |> rvest::html_elements(paste0('span[title="', x, '"]')) |> 
      rvest::html_text() |> tolower() |> trimws()
  } )

  names(lista) <- categories_count$x

  lista_count <- lapply(lista, count_vec)

  list(categories_count , lista_count )
}


#' generate a list of bar/column plots for each category
#'
#' @params counts the counting of categories, generated by count_categores.
gen_plots <- function(counts) {

  lapply(count$x, \(x) {
    lista_count[[x]] |> 
        head(20) |> 
        # ggplot(aes(x= reorder(x, desc(freq)),y=freq, fill = freq)) +
        ggplot(aes(x= reorder(x, freq),y=freq, fill = freq)) +
        # ggplot(aes(x = reorder(x, freq),y=freq, fill = freq)) +
          geom_col() +
          geom_label(aes(label = freq), fill= "white") +
          coord_flip() +
          theme_minimal() +
          theme(legend.position = "none", plot.title.position = "plot") +
            labs(title = paste0('Frequent terms in category: "', x, '"')) +
          xlab("The 20 more frequent terms in category")
    })
}


